serverAddr = "*"
serverPort = 7000

# 认证配置
auth.method = "token"
auth.token = "*"

# 监控
webServer.addr = "127.0.0.1"
webServer.port = 7400
webServer.user = "admin"
webServer.password = "admin123"

# 日志配置
log.to = "frpc.log"
log.level = "info"

[[proxies]]
name = "nginx"
type = "tcp"
enabled = true
localIP = "192.168.1.11"
localPort = 80
remotePort = 7505

[[proxies]]
name = "test"
type = "tcp"
enabled = true
localIP = "127.0.0.1"
localPort = 7890
remotePort = 7890
