serverAddr = "162.14.77.110"
serverPort = 7000

# 认证配置
auth.method = "token"
auth.token = "d4c2dc7262c3d97bcaf3c2d1201282e3"

# 监控
webServer.addr = "127.0.0.1"
webServer.port = 7400

# 日志配置
log.to = "frpc.log"
log.level = "info"

[[proxies]]
name = "test"
type = "tcp"
enabled = true
localIP = "127.0.0.1"
localPort = 7896
remotePort = 7800

[[proxies]]
name = "4234"
type = "tcp"
enabled = true
localIP = "127.0.0.1"
localPort = 7890
remotePort = 7600
